name: Release On Tag

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  id-token: write

jobs:
  release:
    uses: ./.github/workflows/release.yml
    with:
      create-tag: false
